# Notebook: Instalación y Operaciones Básicas en NumPy

## Sección 1: Instalación y verificación

In [1]:
# (Este paso se realiza en consola, no en el notebook)

# pip install numpy
# conda install numpy

Verificar instalación desde Python:

In [ ]:
import numpy as np
print("NumPy version:", np.__version__)


## 🧩 Sección 2: Creación de Arrays

### 🔹 1. Array desde una lista

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
print("Array desde lista:", array1)

### 🔹 3. Array de unos

In [ ]:
ones_array = np.ones(5)
print("Array de unos:", ones_array)

In [ ]:
O_array =np.zeros(5)
print("Array de ceros:", O_array)

NameError: name 'np' is not defined

In [ ]:
o_array=np.ones(10)
print("Array de unos:", o_array)

### 🔹 4. Secuencia de valores

In [ ]:
sequence_array = np.arange(0, 10, 2)
print("Array de secuencia:", sequence_array)

### 🔹 5. Array bidimensional

In [ ]:
matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz 2D:", matrix_2d)

In [1]:
matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("tamaño de la matriz 2D:", matrix_2d.size)
print("dimensiones de la matriz 2D:", matrix_2d.ndim)
print("forma de la matriz 2D:", matrix_2d.shape)

NameError: name 'np' is not defined

## 🧩 Sección 3: Operaciones Básicas con Arrays

### 🔹 1. Suma y multiplicación

In [ ]:
b = np.array([5, 6, 7, 8, 9])
suma = array1 + b
producto = array1 * b
print("Suma de arrays:", suma)
print("Producto elemento a elemento:", producto)


### 🔹 2. Funciones matemáticas

In [ ]:
raiz = np.sqrt(array1)
seno = np.sin(array1)
exponencial = np.exp(array1)
print("Raíz cuadrada:", raiz)
print("Seno:", seno)
print("Exponencial:", exponencial)


### 🔹 3. Estadísticas básicas

In [ ]:
print("Media:", np.mean(array1))
print("Máximo:", np.max(array1))
print("Mínimo:", np.min(array1))

## 🧩 Sección 4: Manipulación de Arrays

### 🔹 1. Cambio de forma (reshape)


In [ ]:
reshaped_array = np.arange(6).reshape(3, 2)
print("Array reestructurado:", reshaped_array)

### 🔹 2. Transposición

In [ ]:
print("Transpuesto:", reshaped_array.T)

### 🔹 3. Concatenación

In [ ]:
concat_array = np.concatenate([array1, b])
print("Concatenación:", concat_array)

### 🔹 4. División de arrays

In [ ]:
split_array = np.split(array1, 5)
print("División:", split_array)

## 🧪 Sección 5: Ejercicios Extra para Clase

### ✏️ Ejercicio 1:
VERONICA ARGUDO
MARCUS MAYORGA
LUIS IRDOÑEZ


In [3]:
import numpy as np


array = np.arange(1, 16)


matriz = array.reshape(5, 3)

print(matriz)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


### ✏️ Ejercicio 2:
> Crear una matriz identidad de 4x4.




In [4]:
import numpy as np
##matriz identidad
matriz_identidad = np.eye(3)
print("Matriz identidad:\n", matriz_identidad)


Matriz identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### ✏️ Ejercicio 3:
> Generar un array de 10 valores linealmente espaciados entre 0 y 5.



In [ ]:
import numpy as np

valores = np.linspace(0, 5, 10)
print(valores)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### ✏️ Ejercicio 4:
> Concatenar dos arrays 1D y dividir el resultado en tres partes iguales.



In [ ]:
import numpy as np


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


c = np.concatenate((a, b))  


partes = np.split(c, 3)


for i, parte in enumerate(partes):
    print(f"Parte {i+1}:", parte)


Parte 1: [1 2]
Parte 2: [3 4]
Parte 3: [5 6]


### ✏️ Ejercicio 5:
> Crear un array de 10 números aleatorios entre 0 y 1. Calcular su media y desviación estándar.



In [ ]:
import numpy as np


arr = np.random.rand(10)


media = np.mean(arr)


desviacion = np.std(arr)


print("Array:", arr)
print("Media:", media)
print("Desviación estándar:", desviacion)


Array: [0.82040595 0.68363851 0.12106802 0.95326062 0.66758647 0.20218216
 0.34309678 0.25017105 0.93707956 0.65629173]
Media: 0.5634780837773656
Desviación estándar: 0.29400722785796574


### 🔥 Ejercicio 6 (Desafío):
> Crear una función que reciba un array y devuelva otro array normalizado entre 0 y 1 (es decir, valores entre el mínimo y máximo del array).

In [8]:
import numpy as np

def normalizar_array(arr):
    minimo = np.min(arr)
    maximo = np.max(arr)
    if maximo == minimo:
        return np.zeros_like(arr)  
    return (arr - minimo) / (maximo - minimo)


arr = np.array([4, 8, 15, 16, 23, 42])
normalizado = normalizar_array(arr)

print("Original:", arr)
print("Normalizado:", normalizado)


Original: [ 4  8 15 16 23 42]
Normalizado: [0.         0.10526316 0.28947368 0.31578947 0.5        1.        ]
