# Notebook: Instalación y Operaciones Básicas en NumPy

## Sección 1: Instalación y verificación

# (Este paso se realiza en consola, no en el notebook)

# pip install numpy
# conda install numpy

Verificar instalación desde Python:

In [1]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.2.5



## 🧩 Sección 2: Creación de Arrays

### 🔹 1. Array desde una lista

In [2]:
array1 = np.array([1, 2, 3, 4, 5])
print("Array desde lista:", array1)

Array desde lista: [1 2 3 4 5]


### 🔹 3. Array de unos

In [3]:
ones_array = np.ones(5)
print("Array de unos:", ones_array)

Array de unos: [1. 1. 1. 1. 1.]


In [4]:
O_array =np.zeros(5)
print("Array de ceros:", O_array)

Array de ceros: [0. 0. 0. 0. 0.]


In [5]:
o_array=np.ones(10)
print("Array de unos:", o_array)

Array de unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 🔹 4. Secuencia de valores

In [6]:
sequence_array = np.arange(0, 10, 2)
print("Array de secuencia:", sequence_array)

Array de secuencia: [0 2 4 6 8]


### 🔹 5. Array bidimensional

In [7]:
matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz 2D:", matrix_2d)

Matriz 2D: [[1 2 3]
 [4 5 6]]


In [8]:
matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("tamaño de la matriz 2D:", matrix_2d.size)
print("dimensiones de la matriz 2D:", matrix_2d.ndim)
print("forma de la matriz 2D:", matrix_2d.shape)

tamaño de la matriz 2D: 6
dimensiones de la matriz 2D: 2
forma de la matriz 2D: (2, 3)


## 🧩 Sección 3: Operaciones Básicas con Arrays

### 🔹 1. Suma y multiplicación

In [9]:
b = np.array([5, 6, 7, 8, 9])
suma = array1 + b
producto = array1 * b
print("Suma de arrays:", suma)
print("Producto elemento a elemento:", producto)

Suma de arrays: [ 6  8 10 12 14]
Producto elemento a elemento: [ 5 12 21 32 45]



### 🔹 2. Funciones matemáticas

In [10]:
raiz = np.sqrt(array1)
seno = np.sin(array1)
exponencial = np.exp(array1)
print("Raíz cuadrada:", raiz)
print("Seno:", seno)
print("Exponencial:", exponencial)

Raíz cuadrada: [1.         1.41421356 1.73205081 2.         2.23606798]
Seno: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]



### 🔹 3. Estadísticas básicas

In [11]:
print("Media:", np.mean(array1))
print("Máximo:", np.max(array1))
print("Mínimo:", np.min(array1))

Media: 3.0
Máximo: 5
Mínimo: 1


## 🧩 Sección 4: Manipulación de Arrays

### 🔹 1. Cambio de forma (reshape)


In [12]:
reshaped_array = np.arange(6).reshape(3, 2)
print("Array reestructurado:", reshaped_array)

Array reestructurado: [[0 1]
 [2 3]
 [4 5]]


### 🔹 2. Transposición

In [13]:
print("Transpuesto:", reshaped_array.T)

Transpuesto: [[0 2 4]
 [1 3 5]]


### 🔹 3. Concatenación

In [14]:
concat_array = np.concatenate([array1, b])
print("Concatenación:", concat_array)

Concatenación: [1 2 3 4 5 5 6 7 8 9]


### 🔹 4. División de arrays

In [15]:
split_array = np.split(array1, 5)
print("División:", split_array)

División: [array([1]), array([2]), array([3]), array([4]), array([5])]


## 🧪 Sección 5: Ejercicios Extra para Clase

### ✏️ Ejercicio 1:
VERONICA ARGUDO
MARCUS MAYORGA
LUIS IRDOÑEZ


In [16]:
import numpy as np


array = np.arange(1, 16)


matriz = array.reshape(5, 3)

print(matriz)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


### ✏️ Ejercicio 2:
> Crear una matriz identidad de 4x4.




In [17]:
import numpy as np
##matriz identidad
matriz_identidad = np.eye(3)
print("Matriz identidad:\n", matriz_identidad)


Matriz identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### ✏️ Ejercicio 3:
> Generar un array de 10 valores linealmente espaciados entre 0 y 5.



In [18]:
import numpy as np

valores = np.linspace(0, 5, 10)
print(valores)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### ✏️ Ejercicio 4:
> Concatenar dos arrays 1D y dividir el resultado en tres partes iguales.



In [19]:
import numpy as np


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


c = np.concatenate((a, b))  


partes = np.split(c, 3)


for i, parte in enumerate(partes):
    print(f"Parte {i+1}:", parte)


Parte 1: [1 2]
Parte 2: [3 4]
Parte 3: [5 6]


### ✏️ Ejercicio 5:
> Crear un array de 10 números aleatorios entre 0 y 1. Calcular su media y desviación estándar.



In [20]:
import numpy as np


arr = np.random.rand(10)


media = np.mean(arr)


desviacion = np.std(arr)


print("Array:", arr)
print("Media:", media)
print("Desviación estándar:", desviacion)


Array: [0.58693473 0.91757352 0.16794244 0.67231872 0.66292612 0.37543849
 0.23586586 0.27395292 0.89256684 0.02028197]
Media: 0.4805801624352906
Desviación estándar: 0.2941551766297552


### 🔥 Ejercicio 6 (Desafío):
> Crear una función que reciba un array y devuelva otro array normalizado entre 0 y 1 (es decir, valores entre el mínimo y máximo del array).

In [21]:
import numpy as np

def normalizar_array(arr):
    minimo = np.min(arr)
    maximo = np.max(arr)
    if maximo == minimo:
        return np.zeros_like(arr)  
    return (arr - minimo) / (maximo - minimo)


arr = np.array([4, 8, 15, 16, 23, 42])
normalizado = normalizar_array(arr)

print("Original:", arr)
print("Normalizado:", normalizado)


Original: [ 4  8 15 16 23 42]
Normalizado: [0.         0.10526316 0.28947368 0.31578947 0.5        1.        ]
