# 🧠 Indexación Avanzada, Slicing y Broadcasting en NumPy

Este notebook complementa el contenido de la Semana 1 del Tema 2 de la Unidad 2 de Programación II, basado en el libro *Numerical Python* y el material proporcionado por el docente. A continuación, trabajaremos con ejemplos prácticos para dominar:

- Indexación básica y multidimensional
- Slicing y máscaras booleanas
- Broadcasting y sus reglas

# Indexación, Slicing y Broadcasting en NumPy: Fundamentos para Ciencia de Datos

In [1]:
import numpy as np
np.set_printoptions(precision=2)

# Creación de arrays para pruebas
arr1d = np.arange(10)
arr2d = np.arange(20).reshape(4, 5)
arr3d = np.arange(2*3*4).reshape(2, 3, 4)

arr1d, arr2d, arr3d.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 (2, 3, 4))

## 🔢 Indexación Básica y Multidimensional
Accedemos a elementos individuales o subconjuntos específicos:

In [4]:
# Indexación 1D
print("arr1d[0] =", arr1d[0])
print("arr1d[-1] =", arr1d[-1])

# Indexación 2D
print("arr2d[1, 2] =", arr2d[1, 2])
print("arr2d[0] (primera fila) =", arr2d[0])
print("arr2d[:, 1] (segunda columna) =", arr2d[:, 1])#los dos puntos indican que se quiere toda la fila 

arr1d[0] = 0
arr1d[-1] = 9
arr2d[1, 2] = 7
arr2d[0] (primera fila) = [0 1 2 3 4]
arr2d[:, 1] (segunda columna) = [ 1  6 11 16]


## ✂️ Slicing y Slicing Avanzado
Extraemos subconjuntos de arrays:

In [6]:
# Slicing básico
print("arr1d[2:7:2] =", arr1d[2:7:2])
print("arr1d[::-1] =", arr1d[::-1])

# Slicing 2D
print("arr2d[1:3, 2:5] =\n", arr2d[1:3, 2:5])

arr1d[2:7:2] = [2 4 6]
arr1d[::-1] = [9 8 7 6 5 4 3 2 1 0]
arr2d[1:3, 2:5] =
 [[ 7  8  9]
 [12 13 14]]


## 🎭 Máscaras Booleanas
Filtramos datos con condiciones lógicas:

In [7]:
# Máscaras booleanas
mask = arr2d > 10
print("Máscara (arr2d > 10):\n", mask)
print("Filtrado:", arr2d[mask])

# Condiciones combinadas
print("(arr2d > 10) & (arr2d < 15):", arr2d[(arr2d > 10) & (arr2d < 15)])

Máscara (arr2d > 10):
 [[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]]
Filtrado: [11 12 13 14 15 16 17 18 19]
(arr2d > 10) & (arr2d < 15): [11 12 13 14]


## 📦 Broadcasting en NumPy
Operaciones entre arrays de diferentes dimensiones:

In [8]:
# Broadcasting ejemplo
columna = np.arange(4).reshape(4, 1)
fila = np.arange(5).reshape(1, 5)
resultado = columna + fila
print("Columna + Fila (Broadcasting):\n", resultado)

# Verificación de reglas
A = np.ones((3, 1))
B = np.ones((1, 4))
print("A * B (Broadcasting):\n", A * B)

Columna + Fila (Broadcasting):
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
A * B (Broadcasting):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
